version: 2
updates:
  - package-ecosystem: "npm"
    directory: "../../"
    schedule:
      interval: "daily" 
    target-branch: "develop"
    labels:
      - "npm"
      - "dependencies"
    commit-message:
      prefix: "npm dev"
      prefix-development: "dev"
    target-branch: "develop"
